#' The ctgPHYLset class
#'
#' The main class used by the \pkg{ctgPHYL} packages to hold PyClone output
#' data and generated tree results.
#'
#' Methods that operate on ctgPHYLset objectsvcomprise the ctgPHYL workflow.
#'
#' @field cellscapeData A list containing the data to be used by
#'     \code{generate_tree(treeType = "cellscape")} in the
#'     \pkg{ctgPHYL} workflow
#' @field timescapeData A list containing the data to be used by
#'     \code{generate_tree(treeType = "timescape")} in the
#'     \pkg{ctgPHYL} workflow
#' @field mapscapeData A list containing the data to be used by
#'     \code{generate_tree(treeType = "mapscape")} in the
#'     \pkg{ctgPHYL} workflow
#' @field treeList A list containing the simplified igraph representation of
#'     the trees generated by the \pkg{ctgPHYL} workflow
#' @field originalTrees A list containing the trees generated by the
#'     \pkg{ctgPHYL} workflow, in their original formats


#' @name ctgPHYLset
#' @rdname ctgPHYLset
#' @aliases ctgPHYLset-class
#' @exportClass ctgPHYLset
setClass( "ctgPHYLset",
          slots = c(cellscapeData = "list",
                    timescapeData = "list",
                    mapscapeData = "list",
                    treeList = "list",
                    originalTrees = "list"
          )
)
